# Generated by Django 4.1.5 on 2023-06-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='SL_NO',
        ),
    ]
