# Generated by Django 4.1.5 on 2023-06-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_remove_crud_sl_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SL_No', models.IntegerField()),
                ('Item_Name', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Crud',
        ),
    ]
